when@dev:
    debug:
        # Forwards VarDumper Data clones to letters centralized server allowing to inspect dumps on CLI or in your browser.
        # See the "server:dump" command to start letters new server.
        dump_destination: "tcp://%env(VAR_DUMPER_SERVER)%"
