monolog:
    channels:
        - doctrine
        - deprecation
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!request", "!doctrine", "!security"]

        info_handlers:
            type: rotating_file
            path: "%kernel.logs_dir%/info.log"
            level: info
            channels: ~

        error_handlers:
            type: rotating_file
            path: "%kernel.logs_dir%/error.log"
            level: error
            channels: ~

        security:
            type: rotating_file
            path: "%kernel.logs_dir%/security.log"
            level: error
            channels: [security]

        doctrine:
            type: rotating_file
            path: "%kernel.logs_dir%/doctrine.log"
            level: debug
            channels: [doctrine]
        deprecation:
            type: stream
            channels: [deprecation]
            path: php://stderr
            formatter: monolog.formatter.json