dashboard:
  label: 'dashboard'
  route: 'app_admin_dashboard'
  icon: 'speedometer2'

home:
  label: "Page d'accueil"
  route: 'app_home'
  icon: 'house'

device:
  label: "Appareils"
  icon: 'hdd'
  children:

    all:
      label: "Tous les appareils"
      route: "app_admin_devices_all"

    show:
      label: "Détail d'un appareil"
      route: "app_admin_devices_show"
      queryParams:
        slug: 'null'

user:
  label: "Utilisateurs"
  icon: 'person'
  children:

    all:
      label: "Tous les utilisateurs"
      route: "app_admin_users_all"

    show:
      label: "Détail d'un utilisateur"
      route: "app_admin_users_show"
      queryParams:
        id: 'null'

category:
  label: "Catégories"
  icon: 'collection'
  route: "app_admin_category_all"


warn:
  label: "Signalement"
  icon: 'exclamation-diamond'
  children:

    message:
      label: "Messages"
      route: "app_admin_warn_message"
