parameters:
    adressEmailNoReply: '%env(EMAIL_NO_REPLY)%'
    adressEmail: '%env(ADRESS_EMAIL)%'
    dataFixture: '%kernel.project_dir%/dataFixtures/'
    jwtsecret: '%env(JWT_SECRET)%'
    nameProject: '%env(APP_NAME)%'
    urlApiGeoGouv: '%env(URL_API_GEO_GOUV)%'
    urlNominatim: '%env(URL_NOMINATIM)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    # this creates letters service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\JWTService:
        arguments:
            $secret: '%env(JWT_SECRET)%'

    App\Service\HttpClientService:
        arguments:
            $urlApiGeoGouv: '%env(URL_API_GEO_GOUV)%'
            $unsplashAccessKey: '%env(KEY_SECRET_API_UNSPLASH)%'

    App\Service\UploadFileService:
        arguments:
            $dirnameUpload: '%kernel.project_dir%/public/upload/'

    App\DataFixtures\AppFixtures:
        arguments:
            $dataFixture: '%kernel.project_dir%/dataFixtures/'
            $uploadFileDevice: '%kernel.project_dir%/public/upload/devices/'


